#SPDX-License-Identifier: MIT-0
---
# tasks file for sai
- name: install some server
  apt:
     name: apache2
     state: present
     update_cache: yes  
  when: ansible_os_family == "Debian"
- name: installing webswerver on centos
  yum: 
     name: httpd
     state: present
     update_cache: yes
  when: ansible_os_family == "RedHat"
- name: service enabled
  service: 
      name: httpd
      state: started
      enabled: yes
  when: ansible_os_family == "RedHat"
